apiVersion: 1

datasources:
  - name: PostgreSQL-OlistDW
    type: postgres
    url: postgres:5432
    database: olist_dw
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
